echo sort([3,1,2])
echo sort([10,9,'a','B'])
echo sort(['b','A','c'],'i')
echo sort([3,1,2],{a,b -> b - a})
echo uniq([1,1,2,2,3])
echo reverse([1,2,3])
echo map([1,2,3],'v:val*2')
echo map({'a':1},'v:val+1')
echo filter([1,2,3,4],'v:val % 2')
echo join(['a','b'],'-')
echo join([1,2])
echo split('a,b,,c',',')
echo split('a,b,,c',',',1)
echo index([1,2,3],2)
echo index(['A','b'],'a',0,1)
echo add([1],2)
echo insert([1,2],0)
echo insert([1,2],9,1)
echo remove([1,2,3],1)
echo extend([1],[2,3])
echo count([1,1,2],1)
echo max([3,1]) . " " . min([3,1])
echo repeat([1],3)
echo repeat('ab',3)
echo len({'a':1,'b':2})
echo keys({'b':1,'a':2})
echo values({'b':1,'a':2})
echo items({'a':1})
echo has_key({'a':1},'a')
echo get({'a':1},'b','d')
echo deepcopy([[1]])
echo flatten([1,[2,[3]]])
echo range(5)
echo range(1,5,2)
echo reduce([1,2,3],{a,b -> a+b},0)
