" match()'s {start} is a BYTE offset: `str += start` can land mid-character.
echo match('é', ']\{}', 1)
echo match('é', '', 1)
echo match('é', '.', 1)
echo string(matchstr('é', '.', 1))
echo matchend('é', '', 1)
echo string(matchstrpos('é', '.', 1))
echo match('日本語', '.', 1)
echo match('日本語', '.', 2)
echo match('日本語', '.', 3)
echo string(matchstr('日本語abc', '\w', 4))
echo string(matchlist('foo123', '\(\a\+\)\(\d\+\)', 1))
echo string(matchstrpos('foobar', 'o\+', 2))
echo string(matchstr('aébc', '.\+', 2))
echo string(matchstr('abcabc', 'b', 0, 2))
