echo substitute('aXbXc','X','-','g')
echo substitute('abc','\(a\)\(b\)','\2\1','')
echo substitute('abc','b','\U&','')
echo matchstr('foo123bar','\d\+')
echo matchlist('foo123','\(\a\+\)\(\d\+\)')
echo match('hello','l')
echo matchend('hello','l')
echo printf('%5.2f|%-5d|%s','3.14159',42,'x')
echo printf('%05d',-3)
echo printf('%x %X %o %b',255,255,8,5)
echo printf('%e',1234.5)
echo printf('%%')
echo strpart('hello',1,3)
echo stridx('hello','l')
echo strridx('hello','l')
echo tolower('ABC') . toupper('abc')
echo strlen('héllo')
echo strchars('héllo')
echo strwidth('héllo')
echo trim('  x  ')
echo escape('a\b','\')
echo string("a'b")
echo str2nr('0x1f',16)
echo str2nr('12abc')
echo string(str2float('1.5e3'))
echo char2nr('A') . ' ' . nr2char(66)
echo strtrans("\<Esc>")
echo eval('1+2')
echo string(eval('[1,2]'))
echo empty('') . empty([]) . empty(0) . empty({})
echo type('') . type(0) . type([]) . type({}) . type(0.0)
