" `\<` and `\>` compare mb_get_class(), so a script change is a word boundary.
echo substitute('日本語abc', '\<', 'X', 'g')
echo substitute('日本語abc', '\>', 'X', 'g')
echo substitute('abc日本語', '\<', 'X', 'g')
echo substitute('あアa漢한', '\<', 'X', 'g')
echo substitute('あアa漢한', '\>', 'X', 'g')
echo substitute('a😀b', '\<', 'X', 'g')
echo substitute('x₂y', '\<', 'X', 'g')
echo substitute('x²y', '\<', 'X', 'g')
echo substitute('µa', '\<', 'X', 'g')
echo substitute('ªa', '\<', 'X', 'g')
echo substitute('foo bar', '\<', 'X', 'g')
echo split('日本語abc', '\<')
echo matchstr('日本語abc', '\<\w\+')
echo match('日本語abc', '\<a')
echo match('日本語abc', '語\>')
echo substitute('ＡＢ', '\<', 'X', 'g')
