//! Generated by scripts/gen_port_stubs.sh — DO NOT EDIT BY HAND.
//!
//! The not-yet-ported surface of the vimlrs interpreter: one stub per
//! Neovim C function definition (real name + `vendor/<file>:<line>`
//! citation, `unimplemented!()` body). As a function is faithfully
//! ported into the hand-written modules it drops out of this tree on the
//! next regeneration. Counts here are the remaining work, nothing else.
pub mod buffer;
pub mod decode;
pub mod deprecated;
pub mod encode;
pub mod eval;
pub mod ex_eval;
pub mod executor;
pub mod fs;
pub mod funcs;
pub mod list;
pub mod typval;
pub mod userfunc;
pub mod vars;
pub mod window;
