#!/bin/sh
# gen_builtin_signatures.sh — record what real vim's `typename()` prints for
# every builtin Funcref, into `src/ported/eval/builtin_signatures.rs`.
#
# `typename(function('strlen'))` is `func([unknown]): number` in vim. Two facts
# go into that string and only two: the accepted argument count (each required
# argument prints as `[unknown]`, each optional one as `?[unknown]`, varargs as
# `...`) and the function's declared RETURN type. vim never reports a real
# argument type for a builtin — every one of them is `[unknown]` — so no
# argument-type table is needed here, and none is generated.
#
# The argument counts are already carried by `funcs_argc.rs`, but that table is
# transcribed from NEOVIM's `vendor/eval.lua` and can disagree with vim; the
# return type is not carried anywhere. Rather than add a second hand-authored
# table and a `ret_number` -> "number" mapping layer that could be wrong, this
# asks the reference binary and stores its answer VERBATIM — the same "the real
# editor is the oracle" methodology `scripts/parity.sh` uses. A recorded string
# cannot be wrong about what vim prints, because it *is* what vim printed.
#
# The name list also comes from vim (`getcompletion('', 'function')`), so a
# builtin vim gained since the last run appears without anyone maintaining a
# list. Under `-u NONE` no user function can be in that list. A name vimlrs does
# not implement simply never gets looked up.
#
# This is a TABLE GENERATOR from the reference implementation, never an audit
# tool: nothing here measures how complete vimlrs is, and it reads no vimlrs
# source. Regenerate with:  sh scripts/gen_builtin_signatures.sh
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

VIM="${VIM:-$(command -v vim || true)}"
[ -n "$VIM" ] || { echo "no vim on PATH — this generator needs the reference editor" >&2; exit 2; }

OUT="src/ported/eval/builtin_signatures.rs"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
TSV="$TMP/sigs.tsv"

# Ask vim for its own builtin names, then for each one's printed signature.
# Completion spells a zero-argument builtin `argidx()` and every other one
# `abs(`, so both trailing forms are stripped. A name that raises (there is
# none under -u NONE, but a future vim could hide one behind a feature) is
# skipped rather than recorded as an error string.
cat >"$TMP/drv.vim" <<EOF
let s:names = map(getcompletion('', 'function'), {_, v -> substitute(v, '()\$\|(\$', '', '')})
let s:out = []
for s:n in s:names
  try
    call add(s:out, s:n . "\t" . typename(function(s:n)))
  catch
  endtry
endfor
call writefile(s:out, '$TSV')
EOF

"$VIM" -es -u NONE -i NONE -c "verbose source $TMP/drv.vim" -c 'qa!' >/dev/null 2>&1 || true
[ -s "$TSV" ] || { echo "vim produced no signatures — driver failed" >&2; exit 1; }

# A signature is plain text (`func([unknown], ?[unknown]): list<string>`). If one
# ever contains a quote or backslash the emitted Rust would be malformed, so
# refuse rather than write a broken table.
if grep -q '["\\]' "$TSV"; then
  echo "a recorded signature contains a quote or backslash — refusing to emit" >&2
  exit 1
fi

REF="$("$VIM" --version | head -1)"

{
  cat <<HEADER
//! GENERATED by scripts/gen_builtin_signatures.sh — DO NOT EDIT.
//!
//! What real vim prints for \`typename(function({name}))\`, recorded verbatim
//! from the reference binary:
//!
//!   $REF
//!
//! vim renders a builtin's every argument as \`[unknown]\` (required) or
//! \`?[unknown]\` (optional) and never as its real type, so the only per-builtin
//! facts in these strings are the argument COUNT and the RETURN type. Storing
//! vim's own output means no \`ret_*\` -> type-name mapping layer can be wrong.
//!
//! Used by \`type_name_of()\` (\`funcs.rs\`) for \`typename()\` of a builtin
//! Funcref. A legacy \`:function\` prints \`func(...): any\` and needs no entry;
//! a lambda's shape follows from its declared parameter count.

/// \`(name, signature)\`, sorted by name for binary search.
pub const BUILTIN_SIGNATURE: &[(&str, &str)] = &[
HEADER

  LC_ALL=C sort "$TSV" | awk -F'\t' 'NF == 2 { printf "    (\"%s\", \"%s\"),\n", $1, $2 }'

  echo "];"
} >"$OUT"

COUNT=$(grep -c '^    ("' "$OUT")
echo "wrote $OUT ($COUNT signatures from $REF)"
